# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "TurtleBot3_Waffle_Pi"
  limits:
    linear: [0.22, 1.0] # velocity, acceleration
    angular: [0.22, 1.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.4 # radius in m
    vicinity: 0.15 # radius in m
  reversible: True # whether robots in this fleet can reverse
  # TODO Update battery parameters with actual specs
  battery_system:
    voltage: 12.0 # V
    capacity: 5.0 # Ahr
    charging_current: 1.5 # A
  mechanical_system:
    mass: 1.8 # kg
    moment_of_inertia: 0.036 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 5.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
  finishing_request: "park" # [park, charge, nothing]
  robots:
    turtlebot3_waffle_pi_1:
      charger: "turtlebot3_waffle_pi_charging_station"

fleet_manager:
  ip: "127.0.0.1"
  port: 22012
  user: "some_user"
  password: "some_password"
  robot_state_update_frequency: 10.0
